# Comparison Operators as ufuncs

In [2]:
import numpy as np

In [3]:
x = np.array([1, 2, 3, 4, 5])
x < 3

array([ True,  True, False, False, False])

In [4]:
(2 * x) == (x ** 2)

array([False,  True, False, False, False])

In [5]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [6]:
x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

# Working with Boolean Arrays

In [8]:
np.count_nonzero(x < 6)

8

In [10]:
np.sum(x < 6)

8

In [11]:
np.sum(x < 6, axis=1)

array([4, 2, 2])

In [12]:
np.any(x > 8)

True

In [13]:
np.any(x < 0)

False

In [14]:
np.all(x < 10)

True

In [15]:
np.all(x < 8, axis=1)

array([ True, False,  True])

## Boolean Arrays as Masks

In [17]:
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [18]:
x < 5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [19]:
x[x < 5]

array([0, 3, 3, 3, 2, 4])