In [1]:
import numpy as np

In [6]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.0, 68.0, 61.5]

In [7]:
data = np.zeros(4, dtype={'names': ('name', 'age', 'weight'),
                          'formats': ('U10', 'i4', 'f8')})
data.dtype

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [8]:
data['name'] = name
data['age'] = age
data['weight'] = weight
data

array([('Alice', 25, 55. ), ('Bob', 45, 85. ), ('Cathy', 37, 68. ),
       ('Doug', 19, 61.5)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [9]:
data['name']

array(['Alice', 'Bob', 'Cathy', 'Doug'], dtype='<U10')

In [10]:
data[0]

('Alice', 25, 55.)

In [11]:
data[-1]['name']

'Doug'

In [15]:
data[data['age'] < 30]

array([('Alice', 25, 55. ), ('Doug', 19, 61.5)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [16]:
data['age'] < 30

array([ True, False, False,  True])

In [17]:
data[[0, 2]]

array([('Alice', 25, 55.), ('Cathy', 37, 68.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

# Creating Structured Arrays

In [18]:
np.dtype({'names': ('name', 'age', 'weight'),
          'formats': ('U10', 'i4', 'f8')})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [20]:
np.dtype({'names': ('name', 'age', 'weight'),
         'formats': ((np.str_, 10), int, np.float32)})

dtype([('name', '<U10'), ('age', '<i8'), ('weight', '<f4')])

In [21]:
np.dtype([('name', 'S10'), ('age', 'i4'), ('weight', 'f8')])

dtype([('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])

In [22]:
np.dtype('S10, i4, f8')

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

# RecordArrays: Structured Arrays with a Twist

In [23]:
data['age']

array([25, 45, 37, 19], dtype=int32)

In [24]:
data_rec = data.view(np.recarray)
data_rec.age

array([25, 45, 37, 19], dtype=int32)

In [25]:
%timeit data['age']
%timeit data_rec['age']
%timeit data_rec.age

124 ns ± 1.42 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
3.08 µs ± 58.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
3.97 µs ± 44.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
