In [1]:
import numpy as np
np.random.seed(0)

In [2]:
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

In [4]:
import inspect

inspect.getmembers(x3)

[('T', array([[[8, 0, 4],
          [9, 4, 7],
          [5, 2, 7],
          [1, 5, 9]],
  
         [[1, 1, 9],
          [4, 7, 9],
          [0, 0, 2],
          [3, 6, 4]],
  
         [[5, 9, 8],
          [3, 3, 9],
          [2, 0, 0],
          [3, 8, 4]],
  
         [[9, 9, 1],
          [0, 2, 3],
          [3, 4, 3],
          [3, 4, 6]],
  
         [[8, 0, 1],
          [3, 7, 6],
          [8, 5, 5],
          [7, 1, 4]]])),
 ('__abs__',
  <method-wrapper '__abs__' of numpy.ndarray object at 0x112697440>),
 ('__add__',
  <method-wrapper '__add__' of numpy.ndarray object at 0x112697440>),
 ('__and__',
  <method-wrapper '__and__' of numpy.ndarray object at 0x112697440>),
 ('__array__', <function ndarray.__array__>),
 ('__array_finalize__', None),
 ('__array_function__', <function ndarray.__array_function__>),
 ('__array_interface__',
  {'data': (140726759999024, False),
   'strides': None,
   'descr': [('', '<i8')],
   'typestr': '<i8',
   'shape': (3, 4, 5),
   'version'

In [9]:
import re

attributes = inspect.getmembers(x3)
attrs = [attr for attr in attributes if re.match(r'(ndim|shape|size)', attr[0])]
attrs

[('ndim', 3), ('shape', (3, 4, 5)), ('size', 60)]

In [10]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [18]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [19]:
x2[:2, :3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [20]:
x2[:3, ::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [21]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [22]:
x2[:, 0]

array([12,  7,  1])

In [23]:
x2[0, :]

array([12,  5,  2,  4])

In [24]:
x2[0]

array([12,  5,  2,  4])

## Subarrays as no-copy views

In [25]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [32]:
x2_sub = x2[:2, :2]
x2_sub

array([[12,  5],
       [ 7,  6]])

In [34]:
x2_sub[0, 0] = 99
x2_sub

array([[99,  5],
       [ 7,  6]])

In [35]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

## Creating copies of arrays

In [36]:
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy

array([[99,  5],
       [ 7,  6]])

In [37]:
x2_sub_copy[0, 0] = 42
x2_sub_copy

array([[42,  5],
       [ 7,  6]])

In [38]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [39]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [40]:
# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [41]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [42]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [43]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

# Array Concatenation and Splitting

## Concatenation of arrays

In [46]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [47]:
z = [99, 99, 99]
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [48]:
grid = np.array([[1, 2, 3],
                [4, 5, 6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [49]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [51]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                [6, 5, 4]])
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [53]:
y = np.array([[99],
             [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

## Splitting of arrays

In [54]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
x1, x2, x3

(array([1, 2, 3]), array([99, 99]), array([3, 2, 1]))

In [55]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [57]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [59]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
