# The slowness of Loops

In [1]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [4]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

2.19 s ± 10.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
%timeit [1.0 / value for value in big_array]

2.05 s ± 22.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


# Introducing UFuncs

In [6]:
%timeit 1.0 / big_array

3.04 ms ± 195 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# Trigonometric functions

In [8]:
theta = np.linspace(0, np.pi, 3)
print('theta:', theta)
print('sin(theta)', np.sin(theta))
print('cos(theta)', np.cos(theta))
print('tan(theta)', np.tan(theta))

theta: [0.         1.57079633 3.14159265]
sin(theta) [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [9]:
x = [-1, 0, 1]
print('x:', x)
print('arcsin(x):', np.arcsin(x))
print('arccos(x):', np.arccos(x))
print('arctan(x):', np.arctan(x))

x: [-1, 0, 1]
arcsin(x): [-1.57079633  0.          1.57079633]
arccos(x): [3.14159265 1.57079633 0.        ]
arctan(x): [-0.78539816  0.          0.78539816]


## Specialized ufuncs

In [10]:
from scipy import special

In [11]:
x = [1, 5, 10]
print('gamma(x):', special.gamma(x))

gamma(x): [1.0000e+00 2.4000e+01 3.6288e+05]


# Advanced Ufunc Features

## Specifying output

In [12]:
x = np.arange(5)
y = np.zeros(10)
np.power(2, x, out=y[::2])
y

array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

## Aggregates

In [14]:
x = np.arange(1, 6)
np.add.reduce(x)

15

In [15]:
np.multiply.reduce(x)

120

In [16]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [17]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])