# Ufuncs: Index Preservation

In [1]:
import pandas as pd
import numpy as np

In [31]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [41]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                 columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  7  2  5  4
1  1  7  5  1
2  4  0  9  5

In [4]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [5]:
np.exp(1)

2.718281828459045

In [6]:
np.exp(2)

7.38905609893065

In [7]:
np.exp(3)

20.085536923187668

In [8]:
np.sin(df * np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

# UFuncs: Index Alignment

## Index alignment in Series

In [9]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')

In [10]:
area

Alaska        1723337
Texas          695662
California     423967
Name: area, dtype: int64

In [11]:
population

California    38332521
Texas         26448193
New York      19651127
Name: population, dtype: int64

In [12]:
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [13]:
area.index | population.index

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [14]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A * B

0     NaN
1     4.0
2    18.0
3     NaN
dtype: float64

In [15]:
A.add(B)

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [16]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

## Index alignment in DataFrame

In [52]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                columns=list('AB'))
A

A   B
0  10  10
1   3   7

In [53]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
                columns=list('BAC'))
B

B  A  C
0  7  2  5
1  4  1  7
2  5  1  4

In [48]:
rng = np.random.RandomState(42)
print(rng.randint(0, 10, 4))
print(rng.randint(0, 10, 4))

rng = np.random.RandomState(42)
print(rng.randint(0, 10, 4))
print(rng.randint(0, 10, 4))

[6 3 7 4]
[6 9 2 6]
[6 3 7 4]
[6 9 2 6]


In [54]:
A * B

A     B   C
0  20.0  70.0 NaN
1   3.0  28.0 NaN
2   NaN   NaN NaN

In [57]:
A.stack()

0  A    10
   B    10
1  A     3
   B     7
dtype: int64

In [58]:
A.stack().mean()

7.5

In [61]:
A.mean()

A    6.5
B    8.5
dtype: float64

In [63]:
A + B

A     B   C
0  12.0  17.0 NaN
1   4.0  11.0 NaN
2   NaN   NaN NaN

In [62]:
fill = A.stack().mean()
A.add(B, fill_value=fill)

A     B     C
0  12.0  17.0  12.5
1   4.0  11.0  14.5
2   8.5  12.5  11.5

# Ufuncs: Operations Between DataFrame and Series

In [65]:
A = rng.randint(10, size=(3, 4))
A

array([[2, 6, 4, 8],
       [6, 1, 3, 8],
       [1, 9, 8, 9]])

In [66]:
A - A[0]

array([[ 0,  0,  0,  0],
       [ 4, -5, -1,  0],
       [-1,  3,  4,  1]])

In [67]:
df = pd.DataFrame(A, columns=list('QRST'))
df

Q  R  S  T
0  2  6  4  8
1  6  1  3  8
2  1  9  8  9

In [68]:
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1  4 -5 -1  0
2 -1  3  4  1

In [70]:
df.subtract(df['R'], axis=0)

Q  R  S  T
0 -4  0 -2  2
1  5  0  2  7
2 -8  0 -1  0

In [71]:
halfrow = df.iloc[0, ::2]
halfrow

Q    2
S    4
Name: 0, dtype: int64

In [72]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1  4.0 NaN -1.0 NaN
2 -1.0 NaN  4.0 NaN